/// <reference types="react-scripts" />
declare module '*.png'
declare module '*.PNG'
declare module '*.svg'
declare module '*.jpeg'
declare module '*.jpg'
declare module '*.avif'
declare module '*.mp4'
declare module '*.mov'
declare module '*.pdf'
declare module '*.webp'
